# Copyright 2020 Mavenir
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.global.xgvela.enablexgvelaScaling -}}
{{- $cnfHdr := (dict "" "") -}}
{{- include "cnfTplHeader_2_9" (dict "cnfHdr" $cnfHdr "dot" . ) -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
{{- include "cnfTplMetadata_2_9" (dict "setOffset" "0" "cnfHdr" $cnfHdr "metadata" .Values.componentSpec.deployment.pod_metaspec) }}
spec:
  maxReplicas: {{ .Values.scaling.max_replicas }}
  minReplicas: {{ .Values.scaling.min_replicas }}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: fmaas
  targetCPUUtilizationPercentage: {{ .Values.scaling.target_cpu_percentage }}
{{- end -}}

